name: Build executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build executable
      run: swift build -c release
    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: Modpack
        path: .build/release/Modpack
