name: Build executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build executable
      run: |
        swift build -c release
        ls -a .build
    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: Modpack
        path: .build/release/Modpack
