name: Build executable

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build executable
      run: |
        swift build -c release --arch arm64 --arch x86_64
    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: Modpack
        path: .build/apple/Products/Release/Modpack
